// Test hot-reload with AUTO-GENERATED patches
//
// This test verifies that patches generated by generate-wasm-patch-auto
// work correctly with the jank WASM runtime.

const fs = require('fs');
const path = require('path');

// Path to auto-generated patch
const AUTO_PATCH_PATH = '/Users/pfeodrippe/dev/jank/wasm-clang-interpreter-test/hot-reload-test/auto_patches/ggg_patch.wasm';

console.log('=== jank WASM Hot-Reload Test (AUTO-GENERATED Patches) ===\n');

async function test() {
  // Check if the built jank module exists
  const modulePath = '/Users/pfeodrippe/dev/jank/compiler+runtime/build-wasm/eita.js';

  if (!fs.existsSync(modulePath)) {
    console.log(`Module not found: ${modulePath}`);
    console.log('\nTo build the module, run:');
    console.log('  cd /Users/pfeodrippe/dev/jank/compiler+runtime');
    console.log('  HOT_RELOAD=1 ./bin/emscripten-bundle wasm-examples/eita.jank');
    console.log('\nSkipping test (no pre-built module)');
    return null; // Skip but don't fail
  }

  console.log(`Loading module: ${modulePath}`);

  try {
    const Module = await import(modulePath);
    const mod = await Module.default();

    console.log('\n1. Testing original ggg function (should add 48):');

    // Get the exported ggg function
    const ggg = mod._jank_export_ggg;

    if (!ggg) {
      console.log('   ERROR: _jank_export_ggg not found');
      console.log('   This may happen if the module was not built with HOT_RELOAD=1');
      return false;
    }

    // Test with value 10: expect 10+48 = 58
    const result1 = ggg(10);
    console.log(`   ggg(10) = ${result1} (expected: 58)`);

    if (result1 !== 58) {
      console.log(`   FAIL: Expected 58, got ${result1}`);
      return false;
    }
    console.log(`   PASS`);

    console.log('\n2. Loading AUTO-GENERATED hot-reload patch (with +49):');

    // Check if auto-generated patch exists
    if (!fs.existsSync(AUTO_PATCH_PATH)) {
      console.log(`   ERROR: Auto-generated patch not found: ${AUTO_PATCH_PATH}`);
      console.log('   Run: ./generate-wasm-patch-auto test_auto_patch.jank');
      return false;
    }

    // Copy patch to virtual FS
    const patchBytes = fs.readFileSync(AUTO_PATCH_PATH);
    const patchVfsPath = '/tmp/ggg_auto_patch.wasm';
    mod.FS.writeFile(patchVfsPath, patchBytes);

    console.log(`   Patch size: ${patchBytes.length} bytes (auto-generated)`);
    console.log(`   Loading patch via jank_hot_reload_load_patch()...`);

    // Load the patch
    const loadResult = mod.ccall(
      'jank_hot_reload_load_patch',
      'number',
      ['string'],
      [patchVfsPath]
    );

    if (loadResult !== 0) {
      console.log(`   FAIL: jank_hot_reload_load_patch returned ${loadResult}`);
      return false;
    }
    console.log(`   Patch loaded successfully!`);

    console.log('\n3. Testing hot-reloaded ggg function (should now add 49):');

    // Test again with value 10: expect 10+49 = 59
    const result2 = ggg(10);
    console.log(`   ggg(10) = ${result2} (expected: 59)`);

    if (result2 !== 59) {
      console.log(`   FAIL: Expected 59, got ${result2}`);
      return false;
    }
    console.log(`   PASS - AUTO-GENERATED HOT-RELOAD WORKING!`);

    return true;
  } catch (err) {
    console.error('Error loading module:', err.message);
    console.log('\nThis may happen if the module was not built with HOT_RELOAD=1');
    return false;
  }
}

test()
  .then(success => {
    if (success === null) {
      console.log('\nTest SKIPPED (no pre-built module)\n');
      process.exit(0);
    } else if (success) {
      console.log('\n=== AUTO-GENERATED HOT-RELOAD TEST PASSED! ===');
      console.log('Patches from generate-wasm-patch-auto work correctly!\n');
      process.exit(0);
    } else {
      console.log('\nHot-reload test FAILED\n');
      process.exit(1);
    }
  })
  .catch(err => {
    console.error('\nTest error:', err);
    process.exit(1);
  });
